spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trainingservice?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: yechan
    password: '6625'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  properties:
    hibernate:
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8InnoDBDialect

logging.level:
  org.hibernate.SQL: debug